In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/fivethirtyeight/data/master/nba-elo/nbaallelo.csv"

response = requests.get(url)
df = pd.read_csv(StringIO(response.text))

df.head()

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,...,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
0,1,194611010TRH,NBA,0,1947,11/1/1946,1,0,TRH,Huskies,...,40.294830,NYK,Knicks,68,1300.0000,1306.7233,H,L,0.640065,NaN
1,1,194611010TRH,NBA,1,1947,11/1/1946,1,0,NYK,Knicks,...,41.705170,TRH,Huskies,66,1300.0000,1293.2767,A,W,0.359935,NaN
2,2,194611020CHS,NBA,0,1947,11/2/1946,1,0,CHS,Stags,...,42.012257,NYK,Knicks,47,1306.7233,1297.0712,H,W,0.631101,NaN
3,2,194611020CHS,NBA,1,1947,11/2/1946,2,0,NYK,Knicks,...,40.692783,CHS,Stags,63,1300.0000,1309.6521,A,L,0.368899,NaN
4,3,194611020DTF,NBA,0,1947,11/2/1946,1,0,DTF,Falcons,...,38.864048,WSC,Capitols,50,1300.0000,1320.3811,H,L,0.640065,NaN

In [ ]:
#Which team has the most amount of wins in the dataset?
df['winning_team'] = df['pts'] > df['opp_pts']
wins_per_team = df[df['winning_team']].groupby('team_id').size().sort_values(ascending = False)
wins_per_team.head()

team_id
BOS    3517
LAL    3134
NYK    2855
DET    2430
PHI    2306
dtype: int64

In [ ]:
#Since 2000, which teams have been the most dominant?
df_filtered = df[(df['year_id'] >= 2000) & (df['year_id'] <= 2015)]

df_filtered['winning_team'] = df_filtered['pts'] > df_filtered['opp_pts']

wins = df_filtered[df_filtered['winning_team']]

fran_wins = wins.groupby('fran_id').size().reset_index(name='Wins Since 2000')

fran_wins = fran_wins.rename(columns={'fran_id': 'Team'})

fran_wins.head(30)

<ipython-input-25-c6a23d1e5138>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['winning_team'] = df_filtered['pts'] > df_filtered['opp_pts']

            Team  Wins Since 2000
0          Bucks              603
1          Bulls              650
2      Cavaliers              663
3        Celtics              753
4       Clippers              602
5      Grizzlies              623
6          Hawks              613
7           Heat              828
8        Hornets              326
9           Jazz              723
10         Kings              644
11        Knicks              581
12        Lakers              901
13         Magic              666
14     Mavericks              905
15          Nets              647
16       Nuggets              690
17        Pacers              758
18      Pelicans              663
19       Pistons              742
20       Raptors              602
21       Rockets              743
22        Sixers              638
23         Spurs             1045
24          Suns              773
25       Thunder              737
26  Timberwolves              570
27  Trailblazers              713
28      Warriors              599
29       Wizards              545

In [ ]:
#How many wins does the Thunder franchise have all time?
df['winning_team'] = df['pts'] > df['opp_pts']

team = 'OKC'

team_wins = df[(df['team_id'] == team) & (df['winning_team'])].shape[0]

team_summary = pd.DataFrame([{'Team': team, 'All Time Wins': team_wins}])

team_summary.head()

  Team  All Time Wins
0  OKC            378

In [ ]:
#How many wins does the Thunder have each year?
# Determine if the team won the game
df['winning_team'] = df['pts'] > df['opp_pts']

# Filter for OKC wins
okc_wins_by_year = df[(df['team_id'] == 'OKC') & (df['winning_team'])]

# Group by year_id and count wins
wins_per_year = okc_wins_by_year.groupby('year_id').size().reset_index(name='Wins')

# Rename column for display
wins_per_year = wins_per_year.rename(columns={'year_id': 'Year'})

wins_per_year.head()

   Year  Wins
0  2009    23
1  2010    52
2  2011    64
3  2012    60
4  2013    65